# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 327d6a27349e700add1505799c117cc1b5d9e379c185a517271c8cfaa4f1534e81137929ec1726018cc0d934a5b88817ca15f54c959a936ad9d8eb7e7d107217

test:
  secret_key_base: 071507df15bc9933deab55b2795ca407b8679dedfaadf0ba7403b625b1b174e6d4e5c6fc15e7b9167588bd1c6577f4a227835f80a58ff7fe43b799fe3283f70d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
